### ISSUE TITLE
Heading disappeared

### ISSUE THREAD

**Issue by dracos** [mysociety/gaze#6]
Not sure how this happened?

**Comment by zarino** [comment]
Did it used to look like this?

<img width="1280" alt="screen shot 2018-09-17 at 21 11 38" src="https://user-images.githubusercontent.com/739624/45647663-5193e680-babe-11e8-95ba-4ae3bcd5fbb6.png">

If so, I’d guess that a change was made to the styling of `.site-title` in mysociety-docs-theme sometime near the end of last year / start of this year, and that‘s caused the text to be `text-indent`ed away.

**Comment by zarino** [comment]
Weirdly, however, I can see no such change in https://github.com/mysociety/mysociety-docs-theme – mysterious! 🕵️‍♀️

**Comment by dracos** [comment]
Fixed by setting logo_path to blank and/or setting it not to be a link as it's only one page.
